# Generated by Django 5.2.7 on 2025-10-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fashion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(default='zngtheo@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
